package exceptionPracticies;

public class FinallyDemo {

	public static void main(String[] args) {
		
		int i = 9;
		int j = 0;

		try {
		System.out.println("Result" + i/j);
		}
		catch(Exception e) {
			e.printStackTrace();
		}
		System.out.println("Result for addition " + i+j);
		System.out.println("Result for multiplication " + i*j);
		System.out.println("Result for substraction " + (i-j));


	}

}
